import 'package:coder_protocol/coder_protocol.dart';

/// Feature ownership for every authenticated daemon RPC method.
const Map<String, List<String>> daemonRpcMethodGroups = <String, List<String>>{
  'workspace': <String>[
    RpcMethod.workspaceCatalog,
    RpcMethod.workspaceRegister,
    RpcMethod.workspaceRefresh,
    RpcMethod.workspaceUnregister,
    RpcMethod.directorySuggest,
    RpcMethod.fileSearch,
    RpcMethod.gitBranchesList,
    RpcMethod.worktreeCreate,
    RpcMethod.worktreeArchivePreview,
    RpcMethod.worktreeArchive,
    RpcMethod.projectSettingsGet,
    RpcMethod.projectSettingsSave,
  ],
  'agents': <String>[
    RpcMethod.agentDefinitionList,
    RpcMethod.agentDefinitionGet,
    RpcMethod.agentDefinitionCreate,
    RpcMethod.agentDefinitionUpdate,
    RpcMethod.agentDefinitionArchive,
    RpcMethod.agentDefinitionReset,
    RpcMethod.agentDefinitionValidate,
    RpcMethod.agentToolCatalog,
  ],
  'mcp': <String>[
    RpcMethod.mcpServerList,
    RpcMethod.mcpServerAdd,
    RpcMethod.mcpServerUpdate,
    RpcMethod.mcpServerRemove,
    RpcMethod.mcpServerTest,
    RpcMethod.mcpSecretSet,
  ],
  'prompts': <String>[
    RpcMethod.commandList,
    RpcMethod.skillList,
    RpcMethod.skillGet,
    RpcMethod.skillCreate,
    RpcMethod.skillUpdate,
    RpcMethod.skillDelete,
    RpcMethod.skillSetEnabled,
  ],
  'sessions': <String>[
    RpcMethod.sessionList,
    RpcMethod.sessionSubagentList,
    RpcMethod.sessionCreate,
    RpcMethod.sessionModelSet,
    RpcMethod.sessionModeSet,
    RpcMethod.sessionReasoningEffortSet,
    RpcMethod.sessionPermissionModeSet,
    RpcMethod.sessionServiceTierSet,
    RpcMethod.turnStart,
    RpcMethod.turnCancel,
    RpcMethod.sessionCompact,
    RpcMethod.approvalResolve,
    RpcMethod.userQuestionAnswer,
    RpcMethod.sessionPendingInput,
    RpcMethod.timelineSubscribe,
  ],
  'terminal': <String>[
    RpcMethod.terminalList,
    RpcMethod.terminalCreate,
    RpcMethod.terminalAttach,
    RpcMethod.terminalWrite,
    RpcMethod.terminalResize,
    RpcMethod.terminalTerminate,
    RpcMethod.terminalShellGet,
    RpcMethod.terminalShellSet,
    RpcMethod.permissionDefaultModeGet,
    RpcMethod.permissionDefaultModeSet,
  ],
  'providers': <String>[
    RpcMethod.providerCatalog,
    RpcMethod.providerConnectionsList,
    RpcMethod.providerConnectApiKey,
    RpcMethod.providerConnectNone,
    RpcMethod.providerAuthStart,
    RpcMethod.providerAuthStatus,
    RpcMethod.providerAuthCancel,
    RpcMethod.providerDisconnect,
    RpcMethod.providerCatalogRefresh,
    RpcMethod.providerModelsList,
    RpcMethod.providerDefaultModelGet,
    RpcMethod.providerDefaultModelSet,
    RpcMethod.providerCustomCreate,
    RpcMethod.providerCustomUpdate,
    RpcMethod.providerCustomDelete,
  ],
};

/// Every authenticated method, flattened in deterministic feature order.
final List<String> daemonRpcMethods = List<String>.unmodifiable(
  daemonRpcMethodGroups.values.expand((methods) => methods),
);
