include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    directives_ordering: true
    prefer_final_locals: true
    sort_constructors_first: false
    unawaited_futures: true
    curly_braces_in_flow_control_structures: false
    prefer_initializing_formals: false
    unnecessary_brace_in_string_interps: false
    unnecessary_underscores: false
    use_null_aware_elements: false
