name: coder_app
description: Cross-platform GUI for Tinyrack Coder.
publish_to: none
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ^3.12.2

dependencies:
  coder_client: ^0.1.0
  coder_daemon: ^0.1.0
  coder_protocol: ^0.1.0
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.12
  flutter_riverpod: 3.3.2
  flutter_secure_storage: ^10.3.1
  go_router: ^17.3.0
  meta: ^1.17.0
  riverpod_annotation: 4.0.3
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  uuid: ^4.6.0

dev_dependencies:
  alchemist: ^0.14.0
  build_runner: 2.15.1
  coder_agent: ^0.1.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.4.0
  integration_test:
    sdk: flutter
  riverpod_generator: 4.0.4

flutter:
  uses-material-design: true
