name: relay
description: Opaque WebSocket relay server for Tinest.
version: 0.6.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  relay_protocol: ^0.1.0
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  cliweave:
    git:
      url: https://github.com/tinyrack-net/dart-packages.git
      ref: ccf93d01393d0607e1f5348feb93f19d9c4ff606
      path: packages/cliweave
  test: ^1.26.3
